version: '3'

networks:
  contele:
    driver: bridge

services:

  contele-api:
    build: .

    volumes:
      - /home/node/api

    environment:
      - MONGO_URL=contele-mongo   
    depends_on:
      - contele-mongo

    networks:
      - contele
    links:
      - contele-mongo
     
    container_name: contele-api
    command: yarn dev
    ports:
      - 3333:3333
  
  contele-mongo:
    image: bitnami/mongodb:latest
    container_name: contele-mongo
    restart: always
    volumes:
      - /home/node/api/mongo

    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    ports:
      - 27017:27017

    networks:
      - contele